name: 'Azure Resource Manager Templates'
on: [push]
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout Azure Resource Manager template repository'
        uses: 'actions/checkout@v2'
        with:
          clean: true
          fetch-depth: 1
          lfs: false
          path: ${{ format('{0}/project', github.workspace) }}
          submodules: false
      - name: 'git version'
        uses: 'codacy/git-version@2.2.0'
        with:
          dev-branch: 'develop'
          major-identifier: 'breaking'
          minor-identifier: 'features'
          prefix: '3.'
          release-branch: 'main'
          tool-version: 'latest'
      - env:
          contentVersion: '1.0.0.0'
        name: 'transform Azure Resource Manager templates'
        uses: 'microsoft/variable-substitution@v1'
        with:
          files: '/project/**/*.json'
      - name: 'upload Azure Resource Manager template artifact'
        uses: 'actions/upload-artifact@v2'
        with:
          if-no-files-found: 'error'
          name: 'project'
          path: ${{ format('{0}/project/**/*.json', github.workspace) }}
          retention-days: 13
  deploy:
    needs: 'build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'download Azure Resource Manager template artifact'
        uses: 'actions/download-artifact@v2'
        with:
          name: 'project'
          path: ${{ format('{0}/downloads/arm-templates', github.workspace) }}
      - name: 'login to Azure'
        uses: 'azure/login@v1'
        with:
          allow-no-subscriptions: true
          creds: ${{ secrets.AZURE_APPLICATION_CREDENTIALS }}
          environment: 'AzureCloud'
      - name: 'publish template spec to Azure Resource Group'
        run: |
          $resourceGroupName = 'byteterrace';
          $subscriptionIdOrName = 'byteterrace';
          $templateFilePath = ${{ format('''{0}/downloads/arm-templates/resourceGroupDeployment.json''', github.workspace) }};
          $templateName = 'ResourceGroupDeployment';
          $version = '1.0.0.0';

          az ts create `
              --name $templateName `
              --resource-group $resourceGroupName `
              --subscription $subscriptionIdOrName `
              --template-file $templateFilePath `
              --version $version `
              --yes;
        shell: 'pwsh'
      - name: 'logout of Azure'
        uses: 'azure/CLI@v1'
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
