name: 'Azure Resource Manager Templates'
on: [push]
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout Azure Resource Manager template repository'
        uses: 'actions/checkout@v2'
      - name: 'upload Azure Resource Manager template artifact'
        uses: 'actions/upload-artifact@v2'
        with:
          if-no-files-found: 'error'
          name: 'project'
          path: './**/*.json'
          retention-days: 13
  deploy:
    needs: 'build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'download Azure Resource Manager template artifact'
        uses: 'actions/download-artifact@v2'
        with:
          name: 'project'
          path: '~/downloads/arm-templates'
      - name: 'login to Azure'
        uses: 'azure/login@v1'
        with:
          allow-no-subscriptions: true
          creds: ${{ secrets.AZURE_APPLICATION_CREDENTIALS }}
          environment: 'AzureCloud'
      - name: 'logout of Azure'
        uses: 'azure/CLI@v1'
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
