name: 'Azure Resource Manager Templates'
on: [push]
jobs:
  Azure-Resource-Manager-Templates:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout Azure Resource Manager template repository'
        uses: 'actions/checkout@v2'
      - name: 'create Azure Resource Manager template artifact'
        uses: 'actions/upload-artifact@v2'
        with:
          if-no-files-found: 'error'
          name: 'project'
          path: './**/*.json'
          retention-days: 13
